### PR TITLE
[Fix] Issue 108: Invalid QR code image

### PR DESCRIPTION
**Pull request by JohnyDNU**
Fixed image for all cases: small and large encoded text generates valid image

### CODE REVIEW

**Comment by JohnyDNU** [comment]
This PR fixes issue described here: https://github.com/awesomejerry/react-native-qrcode-svg/issues/108
Works correct for small and big encoded text values

**Comment by arshdefoamed** [comment]
@awesomejerry can we quickly merge this? This is kind of a showstopper. Thanks!!!

**Comment by awesomejerry** [comment]
I'm not currently working with react-native projects anymore. Please let me know if this PR is not working.

**Comment by JChord** [comment]
qrerror
that will cause render error.

**Comment by pauliushchyk** [comment]
> qrerror
> that will cause render error.

I have the same issue because of these changes.

**Comment by dattm97** [comment]
@awesomejerry Can you check issue? It causes render error.

**Comment by velcroz** [comment]
> 
> 
> qrerror
> that will cause render error.

Adding `strokeLinecap={'square'}` to Line 141 in index.js file fixes it for me

**Comment by awesomejerry** [comment]
I've released 6.1.0, which I tested briefly on Expo web and it's working again. If it's still not working, please let me know.

**Pull request merged**
