### PR TITLE
react-native-svg 13 support

### PR DESCRIPTION
**Pull request by GunnarAK**
Unit tests run fine, but I haven't tested this change with the example project for reasons mentioned here: https://github.com/awesomejerry/react-native-qrcode-svg/issues/164#issuecomment-1323521797

### CODE REVIEW

**Review by otech47 — APPROVED** [review]
This is clean and would prevent repos that depend on this package from having to run `npm install --legacy-peer-deps`

**Comment by 1level1** [comment]
Can we please merge this? What is missing?

**Comment by alessandrocapra** [comment]
@awesomejerry I think you're the official creator, any chance you could merge this? If help is needed let us know, but for me this is blocking the upgrade to Expo SDK 47.

**Comment by awesomejerry** [comment]
> @awesomejerry I think you're the official creator, any chance you could merge this? If help is needed let us know, but for me this is blocking the upgrade to Expo SDK 47.

I don't personally use react-native anymore. If this PR runs fine with the recent Expo version, I can merge it ASAP. Have you tried it with an example project?

**Comment by GunnarAK** [comment]
@awesomejerry as mentioned here (https://github.com/awesomejerry/react-native-qrcode-svg/issues/164#issuecomment-1323521797) I personally did not succeed with getting the example project to run in the first place.

I'm not very familiar with Expo, but it shouldn't be that hard to run an example project.

**Comment by wodin** [comment]
It looks to me like this PR is no longer needed after #166 was merged

**Comment by GunnarAK** [comment]
Fixed in #166

**Pull request closed without merging**
